language: swift
osx_image: xcode9.2
cache: cocoapods

before_install:
- bundle update
- bundle exec pod repo update

script:
- bundle exec fastlane test

after_success:
  - bash <(curl -s https://codecov.io/bash)
